//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelericAcademyModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkHour
    {
        public int EployeeID { get; set; }
        public System.DateTime DateT { get; set; }
        public string Task { get; set; }
        public System.TimeSpan HoursT { get; set; }
        public string Comments { get; set; }
    }
}
